//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcadeX.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPedidos
    {
        public int DetalleID { get; set; }
        public Nullable<int> PedidoID { get; set; }
        public Nullable<int> JuegoID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Juegos Juegos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
