//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arcadeX.baseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errores
    {
        public int ErrorID { get; set; }
        public string ErrorMensaje { get; set; }
        public Nullable<int> ErrorSeveridad { get; set; }
        public Nullable<int> ErrorEstado { get; set; }
        public Nullable<System.DateTime> ErrorFecha { get; set; }
    }
}
